### PR TITLE
add z-index support to Canvas renderer

### PR DESCRIPTION
**Pull request by kpym**
This code add a z-index capabilities to the Canvas renderer and solve #62.

I added some tests to show how it works.

### CODE REVIEW

**Comment by tdewolff** [comment]
Thanks for the effort, highly appreciated. I'll try and review the PR as soon as possible.

**Comment by tdewolff** [comment]
Sorry for the long delay, there was some major work in the way. I've incorporated that work and added support for Z indexing. I've opted for a simpler (but potentially slower) algorithm to minimize the chance for bugs. I'd be happy to accept improvements. Thanks for the work in any case!

**Comment by kpym** [comment]
Thanks for considering my request.

I can't see the tests for the new z-index. How it works ?

**Comment by kpym** [comment]
Oh I see, you have just replaced `[]layer{}` by `map[int][]layer`. This is good. This doesn't look to be "potentially slower", and is simpler. This is something I would not have been able to do because I would have been afraid to break something in the code by modifying the type of the `layers` field.

**Pull request closed without merging**
