### PR TITLE
Fixes #103 Respect font weight for @font-face in svg

### LINKED ISSUE #103: SVG Fonts become mixed up when using different font styles (weights)
Using 2 different font stlyes, I noticed, them beeing mixed up in the SVG.

This is how I use the font within my go project:
```golang
import (
	_ "embed"

	"github.com/tdewolff/canvas"
)

//go:embed res/fonts/Roboto-Regular.ttf
var robotoRegular []byte

//go:embed res/fonts/Roboto-Bold.ttf
var robotoBold []byte

var roboto = loadRoboto()

func loadRoboto() *canvas.FontFamily {
	fontFamily := canvas.NewFontFamily("roboto")
	loadFamily(fontFamily, robotoRegular, canvas.FontRegular)
	loadFamily(fontFamily, robotoBold, canvas.FontBold)
	return fontFamily
}

func loadFamily(fontFamily *canvas.FontFamily, data []byte, style canvas.FontStyle) {
	err := fontFamily.LoadFont(data, 0, style)
	if err != nil {
		panic(err)
	}
}
```

When used in a canvas they become indistinguishable in SVG:

```css
@font-face{font-family:'roboto';src:url('data:type/opentype;base64,AAEAAAA...
@font-face{font-family:'roboto';src:url('data:type/opentype;base64,AAEAAAA...
```

Especially when using SubsetFonts on SVG rendering this causes problems.
This could be potentially sorted by using `font-weight` numeric values for the `@font-face` and `style="font:..."` attributes.

PNG,JPEG and PDF look fine.

### PR DESCRIPTION
**Pull request by Xyaren**
Fixes #103

### CODE REVIEW

**Comment by tdewolff** [comment]
Thanks for the PR! Actually, this has a problem: two font faces with different boldness may be using the same font. We want to embed that font only once, hence the `map[*Font]bool`.

**Comment by Xyaren** [comment]
I'm not sure that this is avoidable, as you seem to need a separate `@font-face` for defining the boldness ?

**Comment by tdewolff** [comment]
Not necessarily, you may define a font-face without bold, and then use that font for an element _and_ define font-weight. This would get you a faux style boldness (i.e. fake), though I'm not a 100% sure. I've added a fix for your issue that is based on that assumption, please let me know how that works! Seems to work well for me (Firefox and Evince).

**Comment by Xyaren** [comment]
Works Perfect :)

**Pull request closed without merging**
