### PR TITLE
fix for a test that causes gomobile to error

### PR DESCRIPTION
**Pull request by fredim**
these 2 lines fail for gomobile

### CODE REVIEW

**Comment by tdewolff** [comment]
Thanks for bringing this up! However, with this change those if statements will never be true (a `uint32` can never be bigger than `math.MaxUint32`). I think we need a different solution...

What error do you encounter? `len()` should return an `int`, and `math.MaxUint32` is a constant without a specific type, so I don't think there can be a compiler error, right?

**Comment by fredim** [comment]
hm, i think the length of an `int` is different by platform, and gomobile is putting it into a 32-bit int... 

the exact errors -

     # github.com/tdewolff/canvas/font
     /var/folders/ld/5py10hmd5pd43mnnkdk6g03r0000gn/T/gomobile-work-822185949/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20200608184218-3b9cb6c84f2d/font/util.go:43:20: constant 4294967295 overflows int
     /var/folders/ld/5py10hmd5pd43mnnkdk6g03r0000gn/T/gomobile-work-822185949/pkg/mod/github.com/tdewolff/canvas@v0.0.0-20200608184218-3b9cb6c84f2d/font/util.go:139:20: constant 4294967295 overflows int

**Comment by tdewolff** [comment]
Yes, now it makes sense. I suggest we change the casting from `uint32` to `uint64`, that way it will work on 64-bit architectures, and never evaluate to true on 32-bit architectures. Can you make that change in the PR? Thanks for digging in!

**Comment by fredim** [comment]
i can (and did), there are several other casts of `len` to `uint32` in `util.go`. but i guess the comparison is to `pos` which is also `uint32`

**Comment by tdewolff** [comment]
> i can (and did), there are several other casts of `len` to `uint32` in `util.go`. but i guess the comparison is to `pos` which is also `uint32`

Yes that is correct! (unsigned) integer comparisons when you're close to overflow is pretty tricky! If you notice an error let me know ;-)

**Pull request merged**
