### PR TITLE
Refactor into RenderTextAsPath

### PR DESCRIPTION
**Pull request by oliverpool**
_Closes #55_ 

As suggested into the linked issue, I refactored the unimplemented `RenderText` methods in a `canvas.RenderTextAsPath` method.

### CODE REVIEW

**Comment by oliverpool** [comment]
The link Travis-Github does not seem to work... 
Maybe you need to follow the steps described here: https://travis-ci.community/t/github-pr-is-being-built-but-result-is-not-shown/7025/2

**Comment by tdewolff** [comment]
Thanks for the PR!

I've ran the suggestions from the Travis article, seems like I had two Travis applications with access. Hopefully it is fixed now!

**Comment by tdewolff** [comment]
What were your thoughts on adding this function in this manner instead of adding it to the `Text` struct?

**Comment by oliverpool** [comment]
I also thought about it, but a bit late (you already had merged the PR).

I do agree with you, it would actually make sense (I opened a new PR)

**Pull request merged**
